apiVersion: v2
name: databasus
description: A Helm chart for Databasus - databases backup and management system
type: application
version: 0.0.0
appVersion: "latest"
keywords:
  - postgresql
  - backup
  - database
  - restore
home: https://github.com/databasus/databasus

sources:
  - https://github.com/databasus/databasus
  - https://github.com/databasus/databasus/tree/main/deploy/helm

maintainers:
  - name: Rostislav Dugin
    url: https://github.com/RostislavDugin

icon: https://raw.githubusercontent.com/databasus/databasus/main/frontend/public/logo.svg
