name: Release Charts

on:
  push:
    branches:
      - main
    paths:
      - 'deploy/postgresus/**' 
  workflow_dispatch:

jobs:
  release:
    permissions:
      contents: read
      packages: write

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Read Helm Chart Version
        id: chart
        uses: jacobtomlinson/gha-read-helm-chart@v1 # Use the latest version
        with:
          path: deploy/postgresus

      - name: Helm Setup
        uses: azure/setup-helm@v4
        with:
          version: ${{ steps.chart.outputs.version }}

      - name: Helm Lint and Template Test
        run: |
            # Define the path to your chart
            CHART_PATH=./deploy/postgresus

            echo "Running helm lint..."
            # 1. Helm Lint: Checks chart structure, metadata, and syntax.
            helm lint "$CHART_PATH"
    
            echo "Running helm template dry-run..."
            # 2. Helm Template: Renders the Kubernetes manifests with default values.
            #    The output is piped to 'cat' just to ensure the command runs without error.
            helm template postgresus "$CHART_PATH" | cat
            
            # Optional: Test rendering with specific, non-default values
            echo "Running helm template with custom values..."
            helm template postgresus "$CHART_PATH" -f "$CHART_PATH/values.yaml" -f "./deploy/test-values.yaml" | cat

      - name: Chart | Push
        uses: appany/helm-oci-chart-releaser@v0.5.0
        with:
          name: postgresus
          repository: ${{ github.repository_owner }}
          tag: ${{ steps.chart.outputs.version }}
          path: deploy/postgresus
          registry: ghcr.io
          registry_username: ${{ github.actor }}
          registry_password: ${{ secrets.GITHUB_TOKEN }}
          update_dependencies: 'true' 